name: RISC-V Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: hakarlsson/riscv-picolibc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build inside the RISC-V container
        run: |
          meson setup builddir --cross-file=cross/rv64imac.toml
          ninja -C builddir

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: s3k-elf
          path: |
            builddir/s3k.elf
